import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import TopNav from "@/components/navigation/TopNav";
import LeftNav from "@/components/navigation/LeftNav";
import Footer from "@/components/ui/Footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Dalbhath Kitchen",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark`}
      >

        <div className="min-h-screen mx-auto">
          <div>
            <TopNav />
          </div>

          <div className="grid grid-cols-12 ">
            <div className="col-span-3 border-2 border-amber-900 "><LeftNav /></div>
            <div className="col-span-9 border-2 border-red-900">{children}</div>
          </div>

        </div>

        <div><Footer /></div>


      </body>
    </html>
  );
}
